### ISSUE TITLE
 Issue with Token Not Being Saved in Nuxt After Successful Authentication

### ISSUE THREAD

**Issue by happyjonny** [dev-charles15531/nuxt-fortify#1]
Description:
Hello, I encountered an issue. When using authmode = token, after successfully logging in, PHP returns the following response: `{"token":"38|DV5bepJbux3wk9qXGqhrtnoN3VWt55lv1J1BlizCc2429b66"}`. However, Nuxt does not save the token.

**Comment by dev-charles15531** [comment]
Hello @happyjonny 

use the [fortify-sanctum](https://github.com/dev-charles15531/fortify-sanctum) package, no config needed and it resolves your issue.
