### ISSUE TITLE
Q: Need example on how to use the useApi composable

### ISSUE THREAD

**Issue by mulky-sulaiman** [dev-charles15531/nuxt-fortify#2]
Hello,

I have been trying to use this package as my attempt of porting my previous Fortify/Inertia/Vue project into Fortify/Nuxt stack. 
So far by following the example in your playground, all is working correctly, Thank you  !

Nevertheless, I need the example on how to fetch sanctum api to other custom endpoint outside the preconfigured fortify endpoints. I see that there is useApi composable which my guess is used to do the api call for those endpoints. However, I can not find the example on how to use it, since I am also quite noob at Vue. 

Any direction on how to do his would be very much appreciated.

**Comment by dev-charles15531** [comment]
The useApi composable is a custom $fetch plugin, an example usage to making a `GET` request:

```
const api = useApi() // useApi() is auto imported by nuxt

await api(endpoint, { method: 'GET' })
  .then((res) => {
     console.log(res)
  }).catch(({ response }) => {
     console.log(response)
  })
```

NB: it uses the `baseUrl` set in your nuxt config
